// Code generated by protoc-gen-go. DO NOT EDIT.
// source: events.proto

package grpcpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	duration "github.com/golang/protobuf/ptypes/duration"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Event struct {
	Id                   uint64               `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string               `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Datetime             *timestamp.Timestamp `protobuf:"bytes,3,opt,name=datetime,proto3" json:"datetime,omitempty"`
	Duration             *duration.Duration   `protobuf:"bytes,4,opt,name=duration,proto3" json:"duration,omitempty"`
	Description          string               `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	OwnerId              uint64               `protobuf:"varint,6,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f22242cb04491f9, []int{0}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Event) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Event) GetDatetime() *timestamp.Timestamp {
	if m != nil {
		return m.Datetime
	}
	return nil
}

func (m *Event) GetDuration() *duration.Duration {
	if m != nil {
		return m.Duration
	}
	return nil
}

func (m *Event) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Event) GetOwnerId() uint64 {
	if m != nil {
		return m.OwnerId
	}
	return 0
}

type From struct {
	From                 *timestamp.Timestamp `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *From) Reset()         { *m = From{} }
func (m *From) String() string { return proto.CompactTextString(m) }
func (*From) ProtoMessage()    {}
func (*From) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f22242cb04491f9, []int{1}
}

func (m *From) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_From.Unmarshal(m, b)
}
func (m *From) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_From.Marshal(b, m, deterministic)
}
func (m *From) XXX_Merge(src proto.Message) {
	xxx_messageInfo_From.Merge(m, src)
}
func (m *From) XXX_Size() int {
	return xxx_messageInfo_From.Size(m)
}
func (m *From) XXX_DiscardUnknown() {
	xxx_messageInfo_From.DiscardUnknown(m)
}

var xxx_messageInfo_From proto.InternalMessageInfo

func (m *From) GetFrom() *timestamp.Timestamp {
	if m != nil {
		return m.From
	}
	return nil
}

type CreateRequest struct {
	Event                *Event   `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f22242cb04491f9, []int{2}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetEvent() *Event {
	if m != nil {
		return m.Event
	}
	return nil
}

type CreateResponse struct {
	Event                *Event   `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f22242cb04491f9, []int{3}
}

func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (m *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(m, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

func (m *CreateResponse) GetEvent() *Event {
	if m != nil {
		return m.Event
	}
	return nil
}

type UpdateRequest struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Event                *Event   `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f22242cb04491f9, []int{4}
}

func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(m, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateRequest) GetEvent() *Event {
	if m != nil {
		return m.Event
	}
	return nil
}

type UpdateResponse struct {
	Event                *Event   `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateResponse) Reset()         { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()    {}
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f22242cb04491f9, []int{5}
}

func (m *UpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateResponse.Unmarshal(m, b)
}
func (m *UpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateResponse.Marshal(b, m, deterministic)
}
func (m *UpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateResponse.Merge(m, src)
}
func (m *UpdateResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateResponse.Size(m)
}
func (m *UpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateResponse proto.InternalMessageInfo

func (m *UpdateResponse) GetEvent() *Event {
	if m != nil {
		return m.Event
	}
	return nil
}

type DeleteRequest struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f22242cb04491f9, []int{6}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteResponse struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f22242cb04491f9, []int{7}
}

func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (m *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(m, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

func (m *DeleteResponse) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ListOfRequest struct {
	From                 *timestamp.Timestamp `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ListOfRequest) Reset()         { *m = ListOfRequest{} }
func (m *ListOfRequest) String() string { return proto.CompactTextString(m) }
func (*ListOfRequest) ProtoMessage()    {}
func (*ListOfRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f22242cb04491f9, []int{8}
}

func (m *ListOfRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListOfRequest.Unmarshal(m, b)
}
func (m *ListOfRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListOfRequest.Marshal(b, m, deterministic)
}
func (m *ListOfRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListOfRequest.Merge(m, src)
}
func (m *ListOfRequest) XXX_Size() int {
	return xxx_messageInfo_ListOfRequest.Size(m)
}
func (m *ListOfRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListOfRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListOfRequest proto.InternalMessageInfo

func (m *ListOfRequest) GetFrom() *timestamp.Timestamp {
	if m != nil {
		return m.From
	}
	return nil
}

type ListOfResponse struct {
	Event                []*Event `protobuf:"bytes,1,rep,name=event,proto3" json:"event,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListOfResponse) Reset()         { *m = ListOfResponse{} }
func (m *ListOfResponse) String() string { return proto.CompactTextString(m) }
func (*ListOfResponse) ProtoMessage()    {}
func (*ListOfResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f22242cb04491f9, []int{9}
}

func (m *ListOfResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListOfResponse.Unmarshal(m, b)
}
func (m *ListOfResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListOfResponse.Marshal(b, m, deterministic)
}
func (m *ListOfResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListOfResponse.Merge(m, src)
}
func (m *ListOfResponse) XXX_Size() int {
	return xxx_messageInfo_ListOfResponse.Size(m)
}
func (m *ListOfResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListOfResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListOfResponse proto.InternalMessageInfo

func (m *ListOfResponse) GetEvent() []*Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func init() {
	proto.RegisterType((*Event)(nil), "Event")
	proto.RegisterType((*From)(nil), "From")
	proto.RegisterType((*CreateRequest)(nil), "CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "CreateResponse")
	proto.RegisterType((*UpdateRequest)(nil), "UpdateRequest")
	proto.RegisterType((*UpdateResponse)(nil), "UpdateResponse")
	proto.RegisterType((*DeleteRequest)(nil), "DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "DeleteResponse")
	proto.RegisterType((*ListOfRequest)(nil), "ListOfRequest")
	proto.RegisterType((*ListOfResponse)(nil), "ListOfResponse")
}

func init() {
	proto.RegisterFile("events.proto", fileDescriptor_8f22242cb04491f9)
}

var fileDescriptor_8f22242cb04491f9 = []byte{
	// 425 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0xdd, 0x8a, 0xd3, 0x40,
	0x14, 0xc7, 0x37, 0xd9, 0x36, 0xd6, 0x53, 0x93, 0xc0, 0xe0, 0x45, 0x36, 0x88, 0x1b, 0x72, 0x55,
	0x10, 0xa7, 0xb2, 0xe2, 0xde, 0x89, 0xa0, 0x55, 0x10, 0x14, 0x21, 0x28, 0x82, 0x37, 0x92, 0xee,
	0x9c, 0xd6, 0xc1, 0x26, 0x13, 0x67, 0xa6, 0xfa, 0x40, 0x3e, 0x95, 0x6f, 0x23, 0x9d, 0xc9, 0x94,
	0x4e, 0x4b, 0xb5, 0x7b, 0x39, 0x27, 0xff, 0x8f, 0x73, 0x7e, 0x81, 0x7b, 0xf8, 0x13, 0x5b, 0xad,
	0x68, 0x27, 0x85, 0x16, 0xf9, 0xe5, 0x52, 0x88, 0xe5, 0x0a, 0xa7, 0xe6, 0x35, 0x5f, 0x2f, 0xa6,
	0x9a, 0x37, 0xa8, 0x74, 0xdd, 0x74, 0xbd, 0xe0, 0xe1, 0xbe, 0x80, 0xad, 0x65, 0xad, 0xb9, 0x68,
	0xed, 0xf7, 0xf2, 0x4f, 0x00, 0xc3, 0xd7, 0x9b, 0x44, 0x92, 0x40, 0xc8, 0x59, 0x16, 0x14, 0xc1,
	0x64, 0x50, 0x85, 0x9c, 0x91, 0xfb, 0x30, 0xd4, 0x5c, 0xaf, 0x30, 0x0b, 0x8b, 0x60, 0x72, 0xb7,
	0xb2, 0x0f, 0x72, 0x0d, 0x23, 0x56, 0x6b, 0xdc, 0xd4, 0x64, 0xe7, 0x45, 0x30, 0x19, 0x5f, 0xe5,
	0xd4, 0x56, 0x50, 0x57, 0x41, 0x3f, 0xba, 0x1d, 0xaa, 0xad, 0x96, 0x3c, 0x83, 0x91, 0x6b, 0xce,
	0x06, 0xc6, 0x77, 0x71, 0xe0, 0x9b, 0xf5, 0x82, 0x6a, 0x2b, 0x25, 0x05, 0x8c, 0x19, 0xaa, 0x1b,
	0xc9, 0x3b, 0xe3, 0x1c, 0x9a, 0x55, 0x76, 0x47, 0xe4, 0x02, 0x46, 0xe2, 0x57, 0x8b, 0xf2, 0x2b,
	0x67, 0x59, 0x64, 0x96, 0xbf, 0x63, 0xde, 0x6f, 0x59, 0x79, 0x0d, 0x83, 0x37, 0x52, 0x34, 0x84,
	0xc2, 0x60, 0x21, 0x45, 0x63, 0x6e, 0xfb, 0xf7, 0xbe, 0x46, 0x57, 0x3e, 0x86, 0xf8, 0x95, 0xc4,
	0x5a, 0x63, 0x85, 0x3f, 0xd6, 0xa8, 0x34, 0x79, 0x00, 0x43, 0x43, 0xbd, 0x4f, 0x88, 0xa8, 0x21,
	0x56, 0xd9, 0x61, 0x49, 0x21, 0x71, 0x72, 0xd5, 0x89, 0x56, 0xe1, 0x7f, 0xf4, 0xcf, 0x21, 0xfe,
	0xd4, 0xb1, 0x9d, 0xf8, 0x7d, 0xf2, 0x5b, 0x7b, 0x78, 0xa4, 0xce, 0xd9, 0x4f, 0xaa, 0xbb, 0x84,
	0x78, 0x86, 0x2b, 0x3c, 0x5a, 0x57, 0x16, 0x90, 0x38, 0x41, 0x1f, 0xb8, 0xaf, 0x78, 0x01, 0xf1,
	0x3b, 0xae, 0xf4, 0x87, 0x85, 0x8b, 0xb8, 0x2d, 0x51, 0x0a, 0x89, 0x0b, 0x38, 0xdc, 0xf9, 0xfc,
	0x60, 0xe7, 0xab, 0xdf, 0x21, 0x44, 0x66, 0xa0, 0xc8, 0x23, 0x88, 0x2c, 0x5d, 0x92, 0x50, 0xef,
	0xaf, 0xe4, 0x29, 0xf5, 0xb1, 0x97, 0x67, 0x1b, 0xb1, 0x65, 0x43, 0x12, 0xea, 0x31, 0xce, 0x53,
	0xea, 0x43, 0xb3, 0x62, 0x7b, 0x37, 0x49, 0xa8, 0x47, 0x28, 0x4f, 0xa9, 0x0f, 0xa4, 0x3c, 0x23,
	0x53, 0x00, 0x7b, 0xc1, 0xcc, 0xa6, 0x7b, 0x3c, 0xf2, 0x94, 0xfa, 0xe7, 0xed, 0x1a, 0x3e, 0x23,
	0x7e, 0x3f, 0xc5, 0xf0, 0x04, 0xc6, 0x76, 0xf6, 0x5e, 0xb4, 0xfa, 0xdb, 0x09, 0x8e, 0x97, 0xa3,
	0x2f, 0xd1, 0x52, 0x76, 0x37, 0xdd, 0x7c, 0x1e, 0x19, 0xf2, 0x4f, 0xff, 0x06, 0x00, 0x00, 0xff,
	0xff, 0x51, 0x31, 0xbb, 0xd2, 0x1d, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// EventsClient is the client API for Events service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EventsClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	ListOfDate(ctx context.Context, in *ListOfRequest, opts ...grpc.CallOption) (*ListOfResponse, error)
	ListOfWeek(ctx context.Context, in *ListOfRequest, opts ...grpc.CallOption) (*ListOfResponse, error)
	ListOfMonth(ctx context.Context, in *ListOfRequest, opts ...grpc.CallOption) (*ListOfResponse, error)
}

type eventsClient struct {
	cc grpc.ClientConnInterface
}

func NewEventsClient(cc grpc.ClientConnInterface) EventsClient {
	return &eventsClient{cc}
}

func (c *eventsClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, "/Events/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventsClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, "/Events/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventsClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, "/Events/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventsClient) ListOfDate(ctx context.Context, in *ListOfRequest, opts ...grpc.CallOption) (*ListOfResponse, error) {
	out := new(ListOfResponse)
	err := c.cc.Invoke(ctx, "/Events/ListOfDate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventsClient) ListOfWeek(ctx context.Context, in *ListOfRequest, opts ...grpc.CallOption) (*ListOfResponse, error) {
	out := new(ListOfResponse)
	err := c.cc.Invoke(ctx, "/Events/ListOfWeek", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventsClient) ListOfMonth(ctx context.Context, in *ListOfRequest, opts ...grpc.CallOption) (*ListOfResponse, error) {
	out := new(ListOfResponse)
	err := c.cc.Invoke(ctx, "/Events/ListOfMonth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventsServer is the server API for Events service.
type EventsServer interface {
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
	Update(context.Context, *UpdateRequest) (*UpdateResponse, error)
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
	ListOfDate(context.Context, *ListOfRequest) (*ListOfResponse, error)
	ListOfWeek(context.Context, *ListOfRequest) (*ListOfResponse, error)
	ListOfMonth(context.Context, *ListOfRequest) (*ListOfResponse, error)
}

// UnimplementedEventsServer can be embedded to have forward compatible implementations.
type UnimplementedEventsServer struct {
}

func (*UnimplementedEventsServer) Create(ctx context.Context, req *CreateRequest) (*CreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedEventsServer) Update(ctx context.Context, req *UpdateRequest) (*UpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedEventsServer) Delete(ctx context.Context, req *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (*UnimplementedEventsServer) ListOfDate(ctx context.Context, req *ListOfRequest) (*ListOfResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListOfDate not implemented")
}
func (*UnimplementedEventsServer) ListOfWeek(ctx context.Context, req *ListOfRequest) (*ListOfResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListOfWeek not implemented")
}
func (*UnimplementedEventsServer) ListOfMonth(ctx context.Context, req *ListOfRequest) (*ListOfResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListOfMonth not implemented")
}

func RegisterEventsServer(s *grpc.Server, srv EventsServer) {
	s.RegisterService(&_Events_serviceDesc, srv)
}

func _Events_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventsServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Events/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventsServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Events_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventsServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Events/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventsServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Events_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventsServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Events/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventsServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Events_ListOfDate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOfRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventsServer).ListOfDate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Events/ListOfDate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventsServer).ListOfDate(ctx, req.(*ListOfRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Events_ListOfWeek_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOfRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventsServer).ListOfWeek(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Events/ListOfWeek",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventsServer).ListOfWeek(ctx, req.(*ListOfRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Events_ListOfMonth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOfRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventsServer).ListOfMonth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Events/ListOfMonth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventsServer).ListOfMonth(ctx, req.(*ListOfRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Events_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Events",
	HandlerType: (*EventsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Events_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Events_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Events_Delete_Handler,
		},
		{
			MethodName: "ListOfDate",
			Handler:    _Events_ListOfDate_Handler,
		},
		{
			MethodName: "ListOfWeek",
			Handler:    _Events_ListOfWeek_Handler,
		},
		{
			MethodName: "ListOfMonth",
			Handler:    _Events_ListOfMonth_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "events.proto",
}
